apiVersion: v1
kind: Pod
metadata:
  namespace: deploy-test
  name: pod-with-liveness-check
spec:
  containers:
    - image: k8spatterns/random-generator:1.0
      name: random-generator
      env:
        - name: DELAY_STARTUP
          value: "20"
      resources: {}
      ports:
        - containerPort: 8080
      livenessProbe: 
        httpGet: 
          path: / 
          port: 8080 
        initialDelaySeconds: 30 