# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  acrId: acrtestmumshad
  acrPswd: LRoyTf/oFUZMdHEOXb7bNidtC=lJUlUN

steps:
- script: |
    docker build -t $(acrId).azurecr.io/result:$(build.buildId) ./result
  displayName: 'Build result'

- script: docker build -t $(acrId).azurecr.io/vote:$(build.buildId) ./vote
  displayName: 'Build vote'

- script: docker build -t $(acrId).azurecr.io/worker:$(build.buildId) ./worker
  displayName: 'Build worker'

- script: |
    docker login -u $(acrId) -p $(acrPswd) $(acrId).azurecr.io
    docker push $(acrId).azurecr.io/result:$(build.buildId)
    docker push $(acrId).azurecr.io/vote:$(build.buildId)
    docker push $(acrId).azurecr.io/worker:$(build.buildId)
  displayName: 'Push all images'