apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-mem
  namespace: deloy-test
spec:
  hard:
    requests.cpu: 400m
    requests.memory: 200Mi
    limits.cpu: 600m
    limits.memory: 500Mi

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage
  namespace: deloy-test
spec:
  hard:
    requests.storage: 500Gi
    ssd.storageclass.storage.k8s.io/requests.storage: 200Gi
    standard.storageclass.storage.k8s.io/requests.storage: 300Gi

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: allobjects
  namespace: deloy-test
spec:
  hard:
    pods: 10
    replicationcontrollers: 5
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 4
    services: 5
    services.nodeports: 2
